# -*- coding: utf-8 -*-
"""Random_Forest_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185zG8OEY3qhTxthxeeiKeBDJ-2Hz5Hpk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("/content/Position_Salaries (1).csv")

X=data.iloc[:,1:-1].values
y=data.iloc[:,-1].values

from sklearn.ensemble import RandomForestRegressor

regression=RandomForestRegressor(n_estimators=10,random_state=0)

regression.fit(X,y)

regression.predict([[6.5]])

X_grid=np.arange(min(X),max(X),0.1)
X_grid=X_grid.reshape((len(X_grid),1))
plt.scatter(X,y,color="red")
plt.plot(X_grid,regression.predict(X_grid),color="blue")
plt.title("Random Forest Regression")
plt.xlabel("Position Level")
plt.ylabel("Salary")
plt.show()