# -*- coding: utf-8 -*-
"""polynomial_linearregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQKYAOz8YF8i1prFNDc6v8uowXGxwieR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("/content/Position_Salaries.csv")

X=data.iloc[:,1:-1].values
y=data.iloc[:,-1].values

from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(X,y)

# polynomial
from sklearn.preprocessing import PolynomialFeatures
poly_reg=PolynomialFeatures(degree=4)

X_poly=poly_reg.fit_transform(X)
lin_reg_2=LinearRegression()
lin_reg_2.fit(X_poly,y)

plt.scatter(X,y,color="red")
plt.plot(X,lin_reg.predict(X),color="blue")
plt.show()

plt.scatter(X,y,color="red")
plt.plot(X,lin_reg_2.predict(X_poly),color="blue")
plt.show()

lin_reg.predict([[6.5]])

lin_reg_2.predict(poly_reg.fit_transform([[6.5]]))

