# -*- coding: utf-8 -*-
"""simple_linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oVVZYMQaq7oxLYXYkhh9GqVcHKR9z2yA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("/content/Salary_Data.csv")

X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
data.isnull().sum()

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

plt.scatter(X_train,y_train,color="red")
plt.plot(X_train,regressor.predict(X_train),color="blue")
plt.title("Salary vs Experience (Training Set)")

plt.scatter(X_test,y_test,color="red")
plt.plot(X_train,regressor.predict(X_train),color="blue")
plt.title("Salary vs Experience (Test Set)")

# from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
# import numpy as np

# print("R2 Score:", r2_score(y_test, y_pred))
# print("MSE:", mean_squared_error(y_test, y_pred))
# print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
# print("MAE:", mean_absolute_error(y_test, y_pred))

