# -*- coding: utf-8 -*-
"""Regression_Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhA7m8cB_JCBYrLKDKF9YJ2z6ZrIujLS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv('/content/Position_Salaries (1).csv')

X=data.iloc[:,1:-1].values
y=data.iloc[:,-1].values

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(X,y)

regressor.predict([[6.5]])

X_grid=np.arange(min(X),max(X),0.1)
X_grid=X_grid.reshape((len(X_grid),1))
plt.scatter(X,y,color='red')
plt.plot(X_grid,regressor.predict(X_grid),color='blue')
plt.title('Decision Tree Regression')
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.show()

